version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: pos-app-backend-1
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: pos-app-db-1
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: pos_db
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
    container_name: pos-app-frontend-1
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
