CREATE DATABASE IF NOT EXISTS pos_db;

USE pos_db;

CREATE TABLE IF NOT EXISTS products (
    PRD_ID INT AUTO_INCREMENT PRIMARY KEY,
    CODE CHAR(13) UNIQUE NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS transactions (
    TRD_ID INT AUTO_INCREMENT PRIMARY KEY,
    DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EMP_CD CHAR(10) NOT NULL,
    STORE_CD CHAR(5) NOT NULL,
    POS_NO CHAR(3) NOT NULL,
    TOTAL_AMT DECIMAL(10, 2) NOT NULL,
    TTL_AMT_EX_TAX DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS transaction_details (
    TRD_ID INT NOT NULL,
    DTL_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRD_ID INT,
    PRD_CODE CHAR(13),
    PRD_NAME VARCHAR(50),
    PRD_PRICE DECIMAL(10, 2),
    TAX_CD CHAR(2),
    FOREIGN KEY (TRD_ID) REFERENCES transactions(TRD_ID),
    FOREIGN KEY (PRD_ID) REFERENCES products(PRD_ID)
);

CREATE TABLE IF NOT EXISTS taxes (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CODE CHAR(2) UNIQUE NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    PERCENT DECIMAL(5, 2) NOT NULL
);

INSERT INTO products (CODE, NAME, PRICE) VALUES
('1234567890123', 'Sample Product 1', 9.99),
('2345678901234', 'Sample Product 2', 19.99),
('3456789012345', 'Sample Product 3', 29.99);

-- Add initial tax rates
INSERT INTO taxes (CODE, NAME, PERCENT) VALUES ('1', '10% Tax', 10.00), ('2', '8% Tax', 8.00);
